using BusinessLogicLayer.Concrete;
using DataAccessLayer.Concrete.EntityFramework;
using DataAccessLayer.Concrete.InMemory;
using Entities.Concrete;
CarManager carManager = new CarManager(new EfCarDal());
RentalManager rentalManager=new RentalManager(new EfRentalDal());
Rental rent = new Rental() { CarID = 1, CustomerID = 1, RentDate = DateTime.Parse("12.12.2023"), ReturnDate = DateTime.Parse("14.12.2023") };
var result=rentalManager.Add(rent);
Console.WriteLine(result.Message);
Console.ReadLine();